<?php
use \Drupal\Core\Routing\RouteMatchInterface;
/**
 * Implements hook_help().
 */
function module1_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.module1':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t(' This module prints the current date.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_page_attachments().
 */
function module1_page_attachments(array &$page) {
  // Youtube Embed Code
  $meta_robots = [
    '#tag' => 'script',
    '#attributes' => [
      'src' => "https://www.youtube.com/player_api",
      'async' => TRUE,
    ],
  ];
  $page['#attached']['html_head'][] = [$meta_robots, 'youtube_script'];

}

/**
 * Implements hook_cron()
 */
function module1_cron() {
  \Drupal::logger('module1')->info('My hook works');
}

function module1_theme($existing, $type, $theme, $path) {
  return array(
    'post_list' => array(
      'variables' => array(
        'title' => 'undefined',
        'post1' => 'uno',
        'post2' => 'dos',
        'post3' => 'tres',
        'post4' => 'cuatro',
        'items' => [],
      ),
    ),
  );
}


